examples/rails-latex-demo/config/routes.rb
Rails.application.routes.draw do
  get 'latex_example' => "latex_example#index"
  get 'latex_example/barcode' => "latex_example#barcode"
  get 'latex_example/barcode_as_string' => "latex_example#barcode_as_string"

  root :to => "latex_example#index"
end

examples/rails-latex-demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

examples/rails-latex-demo/app/controllers/latex_example_controller.rb
class LatexExampleController < ApplicationController
  def index
  end

  def barcode
    render :layout => 'barcode', formats: [:pdf]
  end

  def barcode_as_string
    @pdf=render_to_string(action: 'barcode', layout: "barcode", formats: [:pdf])
    self.content_type = 'text/html'

    File.open(file="#{Rails.root}/tmp/a.pdf",'w:binary') do |io|
      io.write(@pdf)
    end

    render text: "wrote #{file}"
  end
end

examples/rails-latex-demo/app/views/latex_example/barcode.pdf.erb
{\titlefont \huge Sample Barcodes}

\section*{Code-39}

\begin{pspicture}(3,1in)
\psbarcode{RAILS-LATEX}{includetext}{code39}
\end{pspicture}

\section*{EAN-8}

\begin{pspicture}(2.5,1in)
\psbarcode{96385074}{includetext}{ean8}
\end{pspicture}

\section*{EAN-13}

\begin{pspicture}(3,1.2in)
\psbarcode[scalex=0.8,scaley=0.8]{9781860742712}{includetext guardwhitespace}{ean13}
\end{pspicture}

\section*{ISBN}

\begin{pspicture}(3,1in)
\psbarcode{978-3-86541-114}{includetext guardwhitespace}{isbn}
\end{pspicture}

examples/rails-latex-demo/app/views/latex_example/index.html.erb
<h1>LatexExample#index</h1>
<ul>
  <li><%= link_to "print", latex_example_path(:format => :pdf) %></li>

  <li><%= link_to "print barcode", latex_example_barcode_path(:format => :pdf) %></li>

  <li><%= link_to "print barcode - with no '.pdf' in url", latex_example_barcode_path %></li>

  <li><%= link_to "generate barcode pdf as string", latex_example_barcode_as_string_path %> and write to <tt><%= "#{Rails.root}/tmp/a.pdf" %></tt> </li>
</ul>

examples/rails-latex-demo/app/views/latex_example/index.pdf.erb
\section*{Example \LaTeX\ to PDF document}

Generated at <%= Time.current %>.

\includegraphics{<%= File.join(Rails.root,'public/example.jpg') %>}

The last page is \pageref{LastPage}.

examples/rails-latex-demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails5LatexDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>